// <auto-generated />
using System;
using ATM.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ATM.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211106232912_UpdateDataInTable1")]
    partial class UpdateDataInTable1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ATM.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfWrongAttempts")
                        .HasColumnType("int");

                    b.Property<string>("PinCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Card");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 5000m,
                            CardNumber = "1111-8888-7777-9999",
                            IsLocked = false,
                            NumberOfWrongAttempts = 0,
                            PinCode = "1111"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 2000m,
                            CardNumber = "1111-2222-3333-4444",
                            IsLocked = false,
                            NumberOfWrongAttempts = 0,
                            PinCode = "1234"
                        });
                });

            modelBuilder.Entity("ATM.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("NameOfOperation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WithdrawnAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("Operation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountBalance = 2220m,
                            CardId = 1,
                            NameOfOperation = "cash withdrawal",
                            Time = new DateTime(2021, 11, 7, 1, 29, 11, 633, DateTimeKind.Local).AddTicks(1514),
                            WithdrawnAmount = 1000m
                        },
                        new
                        {
                            Id = 2,
                            AccountBalance = 2220m,
                            CardId = 1,
                            NameOfOperation = "balance",
                            Time = new DateTime(2021, 11, 7, 1, 29, 11, 635, DateTimeKind.Local).AddTicks(436),
                            WithdrawnAmount = 0m
                        },
                        new
                        {
                            Id = 3,
                            AccountBalance = 1220m,
                            CardId = 1,
                            NameOfOperation = "cash withdrawal",
                            Time = new DateTime(2021, 11, 7, 1, 29, 11, 635, DateTimeKind.Local).AddTicks(461),
                            WithdrawnAmount = 1000m
                        });
                });

            modelBuilder.Entity("ATM.Models.Operation", b =>
                {
                    b.HasOne("ATM.Models.Card", "Card")
                        .WithMany("Operations")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("ATM.Models.Card", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
